export const TRANSACTIONS_HYDRATED = 'transactions/TRANSACTIONS_HYDRATED';

export const BLOCK_ADDED_TO_QUEUE = 'transactions/BLOCK_ADDED_TO_QUEUE';
export const BLOCK_NUMBER_STORAGE_KEY = 'transactions/BLOCK_NUMBER_STORAGE_KEY';
export const BLOCK_UPDATED = 'transactions/BLOCK_UPDATED';
export const INTERESTING_BLOCK_FOUND = 'transactions/INTERESTING_BLOCK_FOUND';
export const SEARCH_FOR_INTERESTING_BLOCKS = 'transactions/SEARCH_FOR_INTERESTING_BLOCKS';
export const SEARCH_FOR_TRANSACTIONS = 'transactions/SEARCH_FOR_TRANSACTIONS';
export const TRANSACTION_FOUND = 'transactions/TRANSACTION_FOUND';
export const TRANSACTION_UPDATE = 'transactions/TRANSACTION_UPDATE';
export const TRANSACTIONS_STORAGE_KEY = 'transactions/TRANSACTIONS_STORAGE_KEY';
export const TRANSACTION_ITEM_STORAGE_KEY = 'transactions/TRANSACTION_ITEM_STORAGE_KEY/';
