export const GET_CURRENCY_PRICE_REQUEST = 'GET_CURRENCY_PRICE_REQUEST';
export const GET_CURRENCY_PRICE_SUCCESS = 'GET_CURRENCY_PRICE_SUCCESS';
export const GET_CURRENCY_PRICE_FAILURE = 'GET_CURRENCY_PRICE_FAILURE';

export const GET_CURRENCY_HISTORY_REQUEST = 'GET_CURRENCY_HISTORY_REQUEST';
export const GET_CURRENCY_HISTORY_SUCCESS = 'GET_CURRENCY_HISTORY_SUCCESS';
export const GET_CURRENCY_HISTORY_FAILURE = 'GET_CURRENCY_HISTORY_FAILURE';
