# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'hoardinvest' do
  pod "HockeySDK", :subspecs => ['AllFeaturesLib']

  pod 'JumioMobileSDK/Netverify', '~>2.10'

end

target 'hoardinvestTests' do

end
