# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'hoardinvest' do
  pod "HockeySDK", :subspecs => ['AllFeaturesLib']

end

target 'hoardinvestTests' do

end
