export const CONTACT_ADDRESS_SELECTION = 'CONTACT_ADDRESS_SELECTION';
export const CONTACT_ADDRESS_REQUESTING = 'CONTACT_ADDRESS_REQUESTING';
export const CONTACT_ADDRESS_SUCCESS = 'CONTACT_ADDRESS_SUCCESS';
export const CONTACT_ADDRESS_FAILURE = 'CONTACT_ADDRESS_FAILURE';

