export const WALLET_INITIALIZE_PASSPHRASE = "WALLET_INITIALIZE_PASSPHRASE";

export const WALLET_TRACK_SYMBOL = "WALLET_TRACK_SYMBOL";
export const WALLET_TRACK_SYMBOL_SUCCESS = "WALLET_TRACK_SYMBOL_SUCCESS";
export const WALLET_TRACK_SYMBOL_ERROR = "WALLET_TRACK_SYMBOL_ERROR";

export const WALLET_IMPORT = "WALLET_IMPORT";
export const WALLET_IMPORT_SUCCESS = "WALLET_IMPORT_SUCCESS";
export const WALLET_IMPORT_ERROR = "WALLET_IMPORT_ERROR";

export const WALLET_UPDATE_BALANCE_REQUESTING =
  "WALLET_UPDATE_BALANCE_REQUESTING";
export const WALLET_UPDATE_BALANCE_SUCCESS = "WALLET_UPDATE_BALANCE_SUCCESS";
export const WALLET_UPDATE_BALANCE_ERROR = "WALLET_UPDATE_BALANCE_ERROR";

export const WALLET_SEND_FUNDS_REQUESTING = "WALLET_SEND_FUNDS_REQUESTING";
export const WALLET_SEND_FUNDS_SUCCESS = "WALLET_SEND_FUNDS_SUCCESS";
export const WALLET_SEND_FUNDS_ERROR = "WALLET_SEND_FUNDS_ERROR";
