export const SYMBOL_ETH = 'ETH';
export const SYMBOL_BOAR = 'BOAR';

export const WALLET_CREATE_REQUESTING = 'WALLET_CREATE_REQUESTING';
export const WALLET_CREATE_SUCCESS = 'WALLET_CREATE_SUCCESS';
export const WALLET_CREATE_ERROR = 'WALLET_CREATE_ERROR';

export const WALLET_UPDATE_BALANCE_REQUESTING = 'WALLET_UPDATE_BALANCE_REQUESTING';
export const WALLET_UPDATE_BALANCE_SUCCESS = 'WALLET_UPDATE_BALANCE_SUCCESS';
export const WALLET_UPDATE_BALANCE_ERROR = 'WALLET_UPDATE_BALANCE_ERROR';

export const WALLET_SEND_FUNDS_REQUESTING = 'WALLET_SEND_FUNDS_REQUESTING';
export const WALLET_SEND_FUNDS_SUCCESS = 'WALLET_SEND_FUNDS_SUCCESS';
export const WALLET_SEND_FUNDS_ERROR = 'WALLET_SEND_FUNDS_ERROR';
