export const TYPE_SEND = 'TYPE_SEND';
export const TYPE_REQUEST = 'TYPE_REQUEST';

export const RECIPIENT_TYPE_ADDRESS = 'RECIPIENT_TYPE_ADDRESS';
export const RECIPIENT_TYPE_OTHER = 'RECIPIENT_TYPE_OTHER';
