export const VERIFICATION_STATUS_REQUESTING = 'kyc/VERIFICATION_STATUS_REQUESTING';
export const VERIFICATION_STATUS_SUCCESS = 'kyc/VERIFICATION_STATUS_SUCCESS';
export const VERIFICATION_STATUS_ERROR = 'kyc/VERIFICATION_STATUS_ERROR';
export const VERIFICATION_STATUS_RETRY = 'kyc/VERIFICATION_STATUS_RETRY';

export const DOCUMENT_VERIFICATION_REQUESTING = 'kyc/DOCUMENT_VERIFICATION_REQUESTING';
export const DOCUMENT_VERIFICATION_SUCCESS = 'kyc/DOCUMENT_VERIFICATION_SUCCESS';
export const DOCUMENT_VERIFICATION_ERROR = 'kyc/DOCUMENT_VERIFICATION_ERROR';
export const DOCUMENT_VERIFICATION_RETRY = 'kyc/DOCUMENT_VERIFICATION_RETRY';

export const INFO_VERIFICATION_CONFIRMATION = 'kyc/INFO_VERIFICATION_CONFIRMATION';
